import { ClerkProvider } from "@clerk/nextjs";
import Head from "next/head";
import Layout from "./layout";
import type { AppProps } from "next/app";
import { api } from "~/utils/api";
import "~/styles/globals.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ClerkProvider {...pageProps}>
      <Layout>
        <Head>
          <title>BookNook</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </Layout>
    </ClerkProvider>
  );
}
export default api.withTRPC(MyApp);
